- hosts: localhost
  tags: [ pre, git]
  vars:
    src: ""
    uni: ".uni/"
    build: "{{uni}}build/"
    ava: "{{uni}}ava/"
    bot: "bot/"
    vm: "{{uni}}vm/"
    repo: [
      { subdir: "{{build}}", repo: "git@github.com:Source-Graph/GitHubActions.Self-hosted.git", name: "GitHubActions.Self-hosted"},
      { subdir: "{{bot}}", repo: "git@github.com:MetaBotAI/Runescape.graph.git", name: "Runescape.graph"},
      { subdir: "{{bot}}", repo: "https://github.com/Villavu/Simba.git", name: "Simba"},
      { subdir: "{{ava}}", repo: "git@github.com:Source-Graph/Pascal.git", name: "Pascal"},
      { subdir: "{{ava}}", repo: "git@github.com:Source-Graph/Pascal.Lazarus-IDE.git", name: "Pascal.Lazarus-IDE"},
      { subdir: "{{ava}}", repo: "git@github.com:Source-Graph/CodeBlocks.git", name: "CodeBlocks"},
      { subdir: "{{ava}}", repo: "git@github.com:Source-Graph/PyCharm.Community.git", name: "PyCharm.Community"},
      { subdir: "{{ava}}", repo: "git@github.com:Source-Graph/VisualStudioCode.git", name: "VisualStudioCode"},
      { subdir: "{{ava}}", repo: "git@github.com:Source-Graph/VSCode.Pascal.git", name: "VSCode.Pascal"},
      { subdir: "{{uni}}", repo: "git@github.com:Source-Graph/ansible.template.git", name: "ansible.template"},
      ]

  tasks:
  - debug:
      msg: "{{item.name}}"
    loop: "{{repo}}"

  - name: Git checkout
    ansible.builtin.git:
      repo: "{{item.repo}}"
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/src/{{item.subdir}}{{item.name}}"
    loop: "{{repo}}"
