- hosts: localhost #, fedora, ubuntu
  vars:
    # Host_vars
    ansible_become_password: u
    ansible_user: "{{lookup('ansible.builtin.env', 'USER')}}"

  roles:
    - Jupyter
    - Jupyter/VSCode Extension
    - Jupyter/bash history
#    - new Project
