- name: Gnome VM
  hosts: default
  remote_user: vagrant
  vars:
    add_path: /snap/bin

  environment:
    PATH: /usr/local/bin:/usr/bin:/bin:/usr/games:{{add_path}}    #:{{ ansible_env.PATH }}


  roles:
    # - AptCacherNg/Client
    # - Gnome/minimal
    # - Gnome/Setting
    # - .temp
    # - os/Change login password
    # - Snapcraft

    - Visual Studio Code/Extension/Ansible
    # - Jupyter
    # - Jupyter/VSCode Extension
    # - Project