- name: Gnome VM
  hosts: default
  remote_user: vagrant
  vars:
    add_path: /snap/bin

  environment:
    PATH: /usr/local/bin:/usr/bin:/bin:/usr/games:{{add_path}}    #:{{ ansible_env.PATH }}


  roles:
  # Dev
    - AptCacherNg/Client
    - Gnome/minimal
    - Gnome/Setting
    - os/Change login password
    - .temp

  # Jupyter
    - Jupyter
    - Jupyter/Notebook
    - Jupyter/VSCode Extension
    # - Jupyter/new Project