- name: Gnome VM
  hosts: default
  remote_user: vagrant

  roles:
    - AptCacherNg/Client
    - Gnome/minimal
    - Gnome/Setting
    - Jupyter
    - Jupyter/VSCode Extension
    # - Project
    - .temp


  tasks:
    - name: Change user password in Vagrant
      ansible.builtin.user:
        name: vagrant
        password: "{{ 'u' | password_hash('sha512', 'tmpsalt') }}"
      when: ansible_user_id == 'vagrant'
      become: true
